package(default_visibility = ["//visibility:public"])

load(
    ":integration_tests_test.bzl",
    "sut_component_test_suite",
    "external_sut_component_test_suite",
    "integration_test_test_suite",
)

sut_component_test_suite()

external_sut_component_test_suite()

integration_test_test_suite()
